apiVersion: v1
entries:
  age-secrets:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-10-26T15:20:09.076636297+01:00"
    description: A Helm chart for Kubernetes
    digest: 2fa772d4f917febccc90603950e6dbb05024247a850fb630694826c20f34c097
    name: age-secrets
    type: application
    urls:
    - https://callmewhatuwant.github.io/sealed-age-operator/age-secrets-0.1.0.tgz
    version: 0.1.0
generated: "2025-10-26T15:20:09.076136355+01:00"
