version: "2"

run:
  allow-parallel-runners: true
  # statt "exclusions.paths"
  skip-dirs:
    - third_party$
    - builtin$
    - examples$

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    # "formatters" gibt's nicht – diese zwei sind Linters:
    - gofmt
    - goimports
  settings:
    # hier rein statt "linters-settings" (das meckerte ja)
    lll:
      line-length: 140
      tab-width: 1
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing

issues:
  # ersetzt "exclusions.rules"
  exclude-rules:
    - path: ^api/
      linters:
        - lll
    - path: ^internal/
      linters:
        - dupl
        - lll
