version: 1

run:
  allow-parallel-runners: true
  skip-dirs:
    - third_party$
    - builtin$
    - examples$

linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - gofmt
    - goimports

linters-settings:
  lll:
    line-length: 140   # <- Einzeiler bis 140 Zeichen erlaubt
    tab-width: 1
  revive:
    rules:
      - name: comment-spacings
      - name: import-shadowing

issues:
  exclude-rules:
    - path: ^api/
      linters: [lll]
    - path: ^internal/
      linters: [dupl, lll]
