apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "age-secrets.fullname" . }}
  labels:
    {{- include "age-secrets.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - security.age.io
    resources:
      - sealedages
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - security.age.io
    resources:
      - sealedages/status
    verbs:
      - get
      - update
      - patch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "age-secrets.fullname" . }}
  labels:
    {{- include "age-secrets.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "age-secrets.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "age-secrets.fullname" . }}
    namespace: {{ .Release.Namespace }}
