site_name: SealedAgeOperator
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - navigation.sections
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

#extra:
  #version:
    #provider: mike
