name: Build & Push Docker

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        default: 'age-secrets-operator'
      variant:
        required: true
        default: 'op'
      tag:
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-${{ inputs.variant }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image }}:${{ inputs.tag }}
